name: Docker build & deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Start Deployment
      uses: remi-espie/docker-remote-deployment-action@v1.5
      with:
        remote_docker_host: respie@162.38.112.152
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
        args: up -d
      env:
        secretkey: ${{ secrets.SECRETKEY }}
        expiresin: ${{ secrets.EXPIRESIN }}
