name: Docker build & deploy
on:
   workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed
   workflow_dispatch:
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create .env file
      run: |
        echo "SECRETKEY=$SECRETKEY" >> .env
        echo "EXPIRESIN=$EXPIRESIN" >> .env
      env:
        EXPIRESIN: ${{ secrets.EXPIRESIN }}
        SECRETKEY: ${{ secrets.SECRETKEY }}
    - name: Start Deployment
      uses: remi-espie/docker-remote-deployment-action@v1.6
      with:
        remote_docker_host: respie@162.38.112.152
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
        args: up --build -d
