name: Docker build & deploy
on:
   workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed
   workflow_dispatch:
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: form
    - name: Create .env file
      run: |
        echo "SECRETKEY=$SECRETKEY" >> .env
        echo "EXPIRESIN=$EXPIRESIN" >> .env
        echo "SMTP_HOST=$SMTP_HOST" >> .env
        echo "SMTP_PORT=$SMTP_PORT" >> .env
        echo "SMTP_USER=$SMTP_USER" >> .env
        echo "SMTP_PASS=$SMTP_PASS" >> .env
      env:
        EXPIRESIN: ${{ secrets.EXPIRESIN }}
        SECRETKEY: ${{ secrets.SECRETKEY }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
    - name: Start Deployment
      uses: remi-espie/docker-remote-deployment-action@v1.6
      with:
        remote_docker_host: respie@162.38.112.152
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
        args: up --build -d
